### ISSUE TITLE
New cows

### ISSUE THREAD

**Issue by jreic** [bhaney/pennbot#6]
Can be grabbed from https://github.com/paulkaefer/cowsay-files/tree/master/cows. I guess the current ones are installed locally somewhere?

**Comment by bhaney** [comment]
The current ones are actually imported from an external library provided by NPM (the Node.js Package Manager). This is the repository that is being used:

https://github.com/piuccio/cowsay

I can always use a custom repository for cowsay rather than this external one...I would just need to point the import to the local repo rather than this NPM repo.

**Comment by jreic** [comment]
The one I pointed to doesn't include the default cowfiles, so I guess an OR of the two would be the right way to go. But actually, there are enough extra cows to throw into the mix that it's probably not needed for now!

**Comment by bhaney** [comment]
resolved with pull request #7 .
